export const handeliMenu = [
  {
    key: 'key7',
    title: 'Banh Mi Sandwich',
    category: 'Banh Mi',
    description:
      'Vietnamese sandwich, served on in-house baked baguette, comes with House Mayo, Liver Pate, Cucumber, Cilantro and Jalapeno (Spicy)',
    price: 8.5,
    rating: 5,
    img: '',
  },
  {
    key: 'key8',
    title: 'Vegetarian Tofu Banh Mi',
    category: 'Banh Mi',
    description:
      'Lightly fried Tofu pan seared with chopped lemongrass and glazed with in house sweet honey sauce. Served on French infused Vietnamese baguette that is made fresh everyday. Banh mi comes with optional garnishes.',
    price: 8.5,
    rating: 4,
    img: 'https://img.cdn4dd.com/p/fit=cover,width=600,format=auto,quality=50/media/photosV2/83acc4db-7c22-4337-b8c3-8b4a9fb2d50b-d2816d58-f1a6-4c38-8541-7881a9316df3-retina-large.jpg',
  },
  {
    key: 'key9',
    title: 'Beef Stew with Banh Mi',
    category: 'Banh Mi',
    description: '',
    price: 14.0,
    rating: 4.5,
    img: '',
  },
  {
    key: 'key10',
    title: 'Beef Pho Noodle Soup',
    category: 'Noodle Soup',
    description:
      'Tradition Vietnamese beef noodle soup featuring rare beef, beef briskets and traditional veggies.',
    price: 15.0,
    rating: 4,
    img: '',
  },
  {
    key: 'key11',
    title: 'Chicken Pho Noodle Soup',
    category: 'Noodle Soup',
    description: '',
    price: 15.0,
    rating: 4.5,
    img: '',
  },
  {
    key: 'key12',
    title: 'Beef Stew Noodle Soup',
    category: 'Noodle Soup',
    description:
      'Slow cooked braised beef in vegetable stew served with clear glass noodle or egg noodle.',
    price: 15.0,
    rating: 5,
    img: 'https://img.cdn4dd.com/p/fit=cover,width=600,format=auto,quality=50/media/photosV2/0095e448-c3bc-41ea-8a59-23cb7cdceaaa-2ae30fe0-05c1-41cc-8f96-408a278f8911-retina-large.jpg',
  },
  {
    key: 'key13',
    title: 'Wonton Noodle Soup',
    category: 'Noodle Soup',
    description:
      'A flavorful Chinese infused dish, served in pork bone broth with egg noodle, hand wrapped pork wontons, and char siu pork.',
    price: 15.0,
    rating: 4,
    img: 'https://img.cdn4dd.com/p/fit=cover,width=600,format=auto,quality=50/media/photosV2/a9db8a16-a38c-455e-96fb-6b436b0dcddf-df3d4343-7d7f-4d84-8981-dec897a6700e-retina-large.jpg',
  },
  {
    key: 'key14',
    title: 'Spicy Beef Noodle Soup (Bun Bo Hue)',
    category: 'Noodle Soup',
    description:
      'A popular Vietnamese soup containing rice vermicelli and beef in bone broth soup. Infused with the aroma of lemongrass and various spices, this dish originate from the Vietnamese royal court of Hue.',
    price: 15.0,
    rating: 4.5,
    img: 'https://img.cdn4dd.com/p/fit=cover,width=600,format=auto,quality=50/media/photosV2/580f8a09-97e0-4d6f-ae21-07700a7e8610-2d9a9552-667d-4c13-a9b6-e12311be57b9-retina-large.jpg',
  },
  {
    key: 'key15',
    title: 'Vegan Pho',
    category: 'Noodle Soup',
    description:
      'Vegetable broth served with rice noodle, carrot, broccoli, tofu and mushrooms. A vegan take on the traditional hearty Vietnamese Pho',
    price: 15.0,
    rating: 3.5,
    img: '',
  },
  {
    key: 'key16',
    title: 'Rice Bowl',
    category: 'Other Entre',
    description:
      'A Hearty rice bowl meal served with BBQ Pork or Chicken, pickled daikon and carrot, cucumber, our home recipe fish sauce and top with green onion oil sauté.',
    price: 11.0,
    rating: 4,
    img: '',
  },
  {
    key: 'key17',
    title: 'Chicken Slaw Salad (Goi Ga)',
    category: 'Other Entre',
    description:
      'Healthy yet tasty, this is a Vietnamese treat made with chicken, lettuce, pickled daikon carrot, Vietnamese coriander (rau ram), and fried shallots, all topped with nuoc cham.',
    price: 11.0,
    rating: 4,
    img: '',
  },
  {
    key: 'key18',
    title: 'Vermicelli Noodle Bowl',
    category: 'Other Entre',
    description:
      'Fresh made vermicelli, pickled veggies and house made vegetarian fish sauce, can be served with choice of Asian BBQ Pork, Chargrilled Chicken, Lemongrass Tofu or Pan Toss Shrimp.',
    price: 15.0,
    rating: 4.5,
    img: '',
  },
  {
    key: 'key19',
    title: 'Grilled Bagguette with Salt Chili',
    category: 'Small Bites',
    description:
      'Toasted sweet buttered Banh Mi that are chopped up and served with sliced pork rolls, Japanese Mayo, and chili sauce.',
    price: 7.0,
    rating: 0,
    img: 'https://img.cdn4dd.com/p/fit=cover,width=600,format=auto,quality=50/media/photosV2/868582ef-c4da-4622-96c9-e2b2403e4141-41fc73c5-bc73-419b-b5de-3ea4a836b150-retina-large.jpg',
  },
  {
    key: 'key20',
    title: 'Spring Rolls (2)',
    category: 'Small Bites',
    description: '',
    price: 7.0,
    rating: 5,
    img: '',
  },
  {
    key: 'key21',
    title: 'Fried Egg Rolls (2)',
    category: 'Small Bites',
    description:
      'Golden fried rolls that was wrapped in flour paper with pork and veggies.',
    price: 6.5,
    rating: 4,
    img: 'https://img.cdn4dd.com/p/fit=cover,width=600,format=auto,quality=50/media/photosV2/fc0f32d4-c8d9-4db9-a007-1e8af4ec0d2e-2c953b04-fdd2-45f4-a2c7-59c65562d0ae-retina-large.jpg',
  },
  {
    key: 'key22',
    title: '',
    category: 'Small Bites',
    description: '',
    price: 15.0,
    rating: 3,
    img: '',
  },
]
